spring.application.name=engineering

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Munch@08

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true